```{r setup, include = FALSE}
knitr::opts_chunk$set(dev="CairoPNG")
```

```{r}
library(tidyverse)
library(ggsci)
library(ggthemes)
```


```{r}

runtime_linear <- tibble('Input size' = c(1000, 1500, 2000, 3000, 4000),
                         Run_1 = c(2.6952764987945557,
                                   7.126229524612427,
                                   9.575998306274414,
                                   20.777942419052124,
                                   35.26130700111389),
                         Run_2 = c(2.893733263015747,
                                   4.859517335891724,
                                   7.42842698097229,
                                   18.85781955718994,
                                   33.00994396209717),
                         Run_3 = c(2.1713099479675293,
                                   6.126751184463501,
                                   9.92412257194519,
                                   20.081256866455078,
                                   37.109997034072876))

runtime_affine <- tibble('Input size' = c(1000, 1500, 2000, 3000, 4000),
                         Run_1 = c(3.6242849826812744,
                                   7.296172857284546,
                                   15.481485605239868,
                                   31.039982318878174,
                                   63.513609647750854),
                         Run_2 = c(3.6066930294036865,
                                   8.10531735420227,
                                   13.905476331710815,
                                   33.32306361198425,
                                   56.1118381023407),
                         Run_3 = c(3.362262725830078,
                                   7.745866775512695,
                                   13.473588705062866,
                                   28.832944631576538,
                                   56.91905903816223))

runtime_linear %>% 
  group_by(`Input size`) %>% 
  mutate(mean_time = mean(c(Run_1, Run_2, Run_3)),
         sd_time = sd(c(Run_1, Run_2, Run_3))) -> runtime_linear

runtime_affine %>% 
  group_by(`Input size`) %>% 
  mutate(mean_time = mean(c(Run_1, Run_2, Run_3)),
         sd_time = sd(c(Run_1, Run_2, Run_3))) -> runtime_affine

```

```{r}
ggplot(data = runtime_linear) +
  geom_line(aes(x = log(`Input size`), y = log(mean_time))) +
  geom_point(aes(x = log(`Input size`), y = log(mean_time))) +
  geom_errorbar(aes(x = log(`Input size`), 
                    ymin = log(mean_time - sd_time), 
                    ymax = log(mean_time + sd_time)),
                width = 0.05) +
  theme_clean() +
  ggtitle("Runtime: global linear gap cost") +
  ylab("log(Time)[s]") +
  xlab("log(Input size)")
```

```{r}
ggplot(data = runtime_affine) +
  geom_line(aes(x = log(`Input size`), y = log(mean_time))) +
  geom_point(aes(x = log(`Input size`), y = log(mean_time))) +
  geom_errorbar(aes(x = log(`Input size`), 
                    ymin = log(mean_time - sd_time), 
                    ymax = log(mean_time + sd_time)),
                width = 0.05) +
  theme_clean() +
  ggtitle("Runtime: affine gap cost") +
  ylab("log(Time)[s]") +
  xlab("log(Input size)")
```





